FROM golang:1.23.3 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o db-migrator ./db-migrator

FROM alpine:latest
WORKDIR /root
COPY --from=builder /app/db-migrator .
ENTRYPOINT ["./db-migrator"]
